defmodule Cherry.Commands.GenAction do
  @doc_text """
  Generates a GitHub Pages deploy workflow for this site.

  ## Usage

      mix cherry.gen.action [--source DIR] [--branch NAME] [--force] [--json]

  Writes `.github/workflows/pages.yml`: build on push to `--branch`
  (default `main`), upload the site, deploy via GitHub's Pages actions.
  The workflow adds `.nojekyll`, and a `CNAME` when the site's `url` is a
  custom domain (skipped for `*.github.io` and subpath `base_path` sites).

  One-time repo setup: Settings → Pages → Source → GitHub Actions.
  """

  @moduledoc @doc_text

  @behaviour Cherry.CLI.Command

  alias Cherry.CLI.{Context, Error}
  alias Cherry.Site

  @workflow_path ".github/workflows/pages.yml"

  @doc "The single-sourced doc text, reused as the mix task's @moduledoc."
  @spec doc() :: String.t()
  def doc, do: @doc_text

  @impl Cherry.CLI.Command
  @spec switches() :: keyword()
  def switches, do: [source: :string, branch: :string, force: :boolean]

  @impl Cherry.CLI.Command
  @spec run(Context.t()) :: {:ok, map()} | {:error, Error.t()}
  def run(%Context{opts: opts}) do
    source = Keyword.get(opts, :source, File.cwd!())
    branch = Keyword.get(opts, :branch, "main")
    path = Path.join(source, @workflow_path)

    with {:ok, site} <- load_site(source),
         :ok <- refuse_overwrite(path, opts) do
      cname = custom_domain(site)

      File.mkdir_p!(Path.dirname(path))
      File.write!(path, workflow(branch, cname))

      {:ok, %{path: @workflow_path, branch: branch, cname: cname}}
    end
  end

  @impl Cherry.CLI.Command
  @spec human(map()) :: iodata()
  def human(%{path: path, cname: cname}) do
    [
      "Wrote #{path}",
      if(cname, do: " (CNAME: #{cname})", else: ""),
      " — enable it once under Settings → Pages → Source → GitHub Actions."
    ]
  end

  defp load_site(source) do
    case Site.load(source) do
      {:ok, site} -> {:ok, site}
      {:error, message} -> {:error, %Error{code: :no_site, message: message}}
    end
  end

  defp refuse_overwrite(path, opts) do
    if File.exists?(path) and not Keyword.get(opts, :force, false) do
      {:error, %Error{code: :exists, message: "#{@workflow_path} already exists (use --force)"}}
    else
      :ok
    end
  end

  # A CNAME only makes sense for an apex/subdomain site on a custom domain;
  # *.github.io and project-pages (subpath) sites never carry one.
  defp custom_domain(%Site{base_path: base_path}) when base_path != "/", do: nil

  defp custom_domain(%Site{url: url}) do
    case URI.parse(url).host do
      nil -> nil
      host -> if String.ends_with?(host, ".github.io"), do: nil, else: host
    end
  end

  defp workflow(branch, cname) do
    cname_step =
      if cname do
        "\n      - run: echo \"#{cname}\" > _site/CNAME"
      else
        ""
      end

    """
    # Generated by `mix cherry.gen.action` — regenerate with --force rather
    # than editing, or delete this header to take ownership.
    name: Deploy to GitHub Pages

    on:
      push:
        branches: [#{branch}]
      workflow_dispatch:

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: pages
      cancel-in-progress: true

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v7

          # Toolchain setup, caching, build, and cherry.check in one step.
          - uses: holsee/cherry/action@#{action_ref()}

          - run: touch _site/.nojekyll#{cname_step}

          - uses: actions/upload-pages-artifact@v5
            with:
              path: _site

      deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        steps:
          - id: deployment
            uses: actions/deploy-pages@v5
    """
  end

  # The action ref tracks the running cherry version: every release tags
  # the repo and action/ ships inside it, so v<version> always resolves
  # for a released cherry. Sites get the action revision that shipped
  # with the cherry that generated their workflow.
  defp action_ref do
    "v" <> to_string(Application.spec(:cherry, :vsn))
  end
end
