defmodule Cherry.Skill do
  @moduledoc """
  Renders the generated half of the agent skill (`skills/cherry/`): a
  complete per-verb command reference sourced from the CLI registry and
  each command's single-sourced doc text, so the skill can never drift
  from the real verb surface.

  `mix ci` gates the committed file against this renderer (see
  `Cherry.SkillTest`); regenerate with `mix run scripts/regen_skill.exs`.
  """

  alias Cherry.CLI.Registry

  @reference_path "skills/cherry/references/commands.md"

  @doc "Repo-relative path of the generated command reference."
  @spec reference_path() :: Path.t()
  def reference_path, do: @reference_path

  @doc "The full generated command reference, one section per verb."
  @spec commands_reference() :: String.t()
  def commands_reference do
    header() <> Enum.map_join(Registry.verbs(), "\n", &verb_section/1)
  end

  defp header do
    """
    <!-- Generated by `mix run scripts/regen_skill.exs` from the CLI verb
         registry. Do not edit by hand — `mix ci` fails when this file is
         stale. -->

    # cherry command reference

    Every command accepts the global flags `--json` (machine-readable
    envelope on stdout) and `--verbose`. Exit codes: 0 success, 1 the
    command ran and failed, 2 usage error. The verbs are identical under
    the standalone binary (`cherry VERB`) and mix (`mix cherry.VERB`).

    """
  end

  defp verb_section(verb) do
    {:ok, command} = Registry.fetch(verb)

    """
    ## cherry #{verb}

    #{flags(command.switches())}

    #{command.doc() |> String.trim() |> demote_headings()}
    """
  end

  # Doc texts carry their own `## Usage` headings; nest them under the
  # per-verb `## cherry VERB` sections.
  defp demote_headings(doc) do
    String.replace(doc, ~r/^##(?=\s)/m, "###")
  end

  defp flags([]), do: "Flags: global only."

  defp flags(switches) do
    rendered = Enum.map_join(switches, ", ", &render_switch/1)
    "Flags: #{rendered} — plus the global flags."
  end

  defp render_switch({name, :boolean}), do: "`#{flag_name(name)}`"
  defp render_switch({name, :string}), do: "`#{flag_name(name)} VALUE`"
  defp render_switch({name, :integer}), do: "`#{flag_name(name)} N`"

  defp flag_name(name) do
    "--" <> String.replace(Atom.to_string(name), "_", "-")
  end
end
